name: Push Code to Backend Branch
on:
  push:
    paths:
      - backend/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy Backend Code
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: backend
          FOLDER: backend
          GITHUB_TOKEN: ${{ secrets.SECRET }}
